eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
mail:
  login: testBlablaChanged
  appAdministratorLastName: Zsolt default
  appAdministratorFirstName: Lazar default
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/family
    username: postgres
    password: mysecret


