eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8101
spring:
  messages:
    basename: messages
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
appname: salary-service
firstname: Zsolt
job: Developer
name2: Vika
job2: astistentka
